---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
        ingress:
          enabled: true
          ingressClassName: alb
          annotations: {
          alb.ingress.kubernetes.io/scheme: internet-facing,
          alb.ingress.kubernetes.io/target-type: ip,
          alb.ingress.kubernetes.io/group.name: gbcluster,
          }

          hosts: [prometheus.example.com]

    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true