apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        ingress:
          enabled: true
          path: /
          hosts:
            - prometheus.example.com
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: gbcluster
          ingressClassName: alb
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.3.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: false