apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-appset
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: appset/
    repoURL: 'https://github.com/moksongmin/containers-sg-green-belt'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  generators:
    - git:
        repoURL: 'https://github.com/moksongmin/containers-sg-green-belt.git'
        revision: HEAD
        directories:
          - path: appset/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/moksongmin/containers-sg-green-belt.git'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: ''
        server: 'https://kubernetes.default.svc'
        namespace: grafana
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
