apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '2048'
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: appset/game-2048/
    repoURL: 'https://github.com/moksongmin/containers-sg-green-belt.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false